### ISSUE TITLE
GSOC 14

### ISSUE THREAD

**Issue by krz** [JuliaLang/IterativeSolvers.jl#23]
Hi
I'm a MS student of applied stochastics with a BS in pure math and like to pick this as a GSOC project. As a first try, I implemented the bicgstab algorithm:
https://github.com/krz/julia-numalg/blob/master/bicgstab.jl
It is working but not ready for commit as I don't really have the hang of the Krylov type yet. Let me know what you think.

**Comment by andreasnoack** [comment]
Overdue
