### ISSUE TITLE
orthogonalization methods

### ISSUE THREAD

**Issue by dane-unltd** [JuliaLang/IterativeSolvers.jl#30]
Just some minor nitpicking:

The authors of the paper you linked to are not saying that MGS and Householder QR are numerically equivalent. But I guess implementing the orthogonalization with Householder would be a bit tedious.

Since classical GS is less stable than MGS it is not really necessary to have it as an option.

**Comment by jiahao** [comment]
Thank you for the correction. I've updated the docs and provided an orthogonalization method using brute force Householder which I think will be useful for testing purposes.

Classical Gram-Schmidt is still useful for some applications, so there's no harm in leaving it in.
