### ISSUE TITLE
Missing dependency on Docile

### ISSUE THREAD

**Issue by jaak-s** [JuliaLang/IterativeSolvers.jl#35]
It seems that IterativeSolvers depends on Docile but does not declare it (at least Pkg.clone("...iterativeSolvers.jl.git") does not install it) and later loading it gives following error in julia v0.3.5.
```
ERROR: Docile not found
 in require at loading.jl:47
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/jaak/.julia/v0.3/IterativeSolvers/src/IterativeSolvers.jl, in expression starting on line 6
```

**Comment by jiahao** [comment]
`Docile` is only required for julia 0.3.x (it is integrated into 0.4-dev), and unfortunately there is currently no way to specify this dependency conditionally in Julia's package manager.

Ref: JuliaLang/julia#6195 MichaelHatherly/Docile.jl#64
