### ISSUE TITLE
Ambiguous definition of *

### ISSUE THREAD

**Issue by jaak-s** [JuliaLang/IterativeSolvers.jl#36]
When loading IterativeSolvers (in julia v0.3.5) following warning is thrown:
```julia
julia> using IterativeSolvers
Warning: New definition 
    *(Any,srft) at /home/jaak/.julia/v0.3/IterativeSolvers/src/rlinalg.jl:301
is ambiguous with: 
    *(AbstractMatrixFcn{T},Any) at /home/jaak/.julia/v0.3/IterativeSolvers/src/common.jl:113.
To fix, define 
    *(AbstractMatrixFcn{T},srft)
before the new definition.
```

**Comment by jiahao** [comment]
This warning will go away once I find the time to rewrite the existing solvers to expose a common API.

**Comment by jiahao** [comment]
I don't remember when exactly this was fixed, but certainly master no longer throws any ambiguity warnings on Julia 0.4 or 0.5.
