### ISSUE TITLE
https://github.com/mschauer/IDRsSolver.jl

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/IterativeSolvers.jl#39]
@astudillor and me ported a basic Induced Dimension Reduction Solver to julia, @tkelman mentioned IterativeSolvers and medium-term I think this could be incorporated into this package. Anyway I harmonized the interface mostly, modulo issues how generic LinearOperators are treated.

**Comment by mschauer** [comment]
Link: https://github.com/mschauer/IDRsSolver.jl

**Comment by mschauer** [comment]
Could I get a feedback here before I do a pull request which is not welcome?

**Comment by jiahao** [comment]
Yes please! Sorry I missed his issue.
