### ISSUE TITLE
How to supply custom MatVec function to eigvals_lanczos?

### ISSUE THREAD

**Issue by xyu40** [JuliaLang/IterativeSolvers.jl#48]
After reading the documentations and the source code (common.jl, krylov,jl, and lanczos.jl), I still have no clues as to how to supply a custom matrix-vector multiplication function to eigvals_lanczos.

I only figures out how to get linear-operators-defined-as-functions, such as A = MatrixFcn{Float64}(4, 4, mulbyA!). Although this works as matrix-vector multiplication, yet when put in eigvals_lanczos(A) it throws error message: 
"`KrylovSubspace{T,OpT}` has no method matching `KrylovSubspace{T,OpT}(::MatrixFcn{Float64}, ::Int64)`".

I will appreciate it greatly if you guys can help me on this.

**Comment by xyu40** [comment]
@andreasnoack Thanks a lot. That fixes the error messages.
Just another quick question, eigvals_lanczos() does not produce the Ritz vectors, right? Is there a quick fix?

**Comment by jiahao** [comment]
No, not currently. However, you can compute the eigenvectors through inverse iteration. `eigvals_lanczos` also needs some work to be more robust.
