### ISSUE TITLE
Change description

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLang/IterativeSolvers.jl#50]
The current repository description reads "Implement Arnoldi and Lanczos methods for svds and eigs".
A better title would be something like the first sentence in the README "IterativeSolvers is a Julia package that provides flexible iterative algorithms for linear algebra."

**Comment by tkelman** [comment]
+1 - @jiahao, @andreasnoack, okay with you?

**Comment by andreasnoack** [comment]
Yes. I think it would be a reasonable change.

**Comment by jiahao** [comment]
I would avoid the word "flexible", since it has a technical meaning in the context of iterative solvers, e.g. [flexible GMRES (pdf)](http://www-users.cs.umn.edu/~saad/PDF/umsi-91-279.pdf), that we do not provide. But otherwise yes, we can have a better description.

**Comment by tkelman** [comment]
generic?

**Comment by jiahao** [comment]
I forgot that changing the description requires owner permissions.

"Iterative algorithms for solving linear systems, eigensystems, and singular value problems" would suffice.

**Comment by tkelman** [comment]
Ah cool, done.
