### ISSUE TITLE
Restriction on square linear systems

### ISSUE THREAD

**Issue by tknopp** [JuliaLang/IterativeSolvers.jl#62]
The README mentions:

`operator A that maps n-dimensional vectors to n-dimensional vectors...`

Is this correct and the package is restricted to square linear systems? Or are non-square systems also within the scope of this package?

**Comment by jiahao** [comment]
I would happily take methods for non-square systems. At the time I don't think I had any methods for nonsquare operators, but this is now out of date now that we have GMRES and iterative SVD.

**Comment by tknopp** [comment]
Thanks for clarification!
