### ISSUE TITLE
Simple example for Matrix-free eigenvalues

### ISSUE THREAD

**Issue by rveltz** [JuliaLang/IterativeSolvers.jl#70]
Hi,

It is possible that you provide a simple example of a Matrix-free eigenvalue problem please?

For example the following example does not work,

`using IterativeSolvers`
`function shiftback!(output, b)`
 `       n = length(b)`
  `      length(output) == n || throw(DimensionMismatch())`
   `     for i = 1:n-1`
    `        output[i+1] = b[i]`
     `   end`
      `  output[1] = b[n]`
      `  output`
`end`
`A = IterativeSolvers.MatrixFcn{Int}(15, 15, shiftback!)`
`IterativeSolvers.eigvals_power(A) `

Thank you,

**Comment by rveltz** [comment]
I solved it with:
`A = IterativeSolvers.MatrixFcn{Float64}(15, 15, shiftback!)`

**Comment by jpfairbanks** [comment]
@rveltz can this issue be closed?

**Comment by francispoulin** [comment]
I realize this is an old issue from 2016, but I tried this example and it doesn't seem to work with the `IterativeSolvers` that I just installed.  Could someone help me with an updated version of this code?  I presume the tools are still there but the syntax has changed?

**Comment by haampie** [comment]
See the docs: https://julialinearalgebra.github.io/IterativeSolvers.jl/dev/getting_started/#matrixfree

**Comment by francispoulin** [comment]
Thank you @haampie , those links are very helpful.
