### ISSUE TITLE
cg with a matrix-vector handle

### ISSUE THREAD

**Issue by ajt60gaibb** [JuliaLang/IterativeSolvers.jl#72]
Is it possible to do `cg` with a matrix-vector function?  For example, 
```
B = randn(3,3)
C(x) = B*x
x = cg( C, randn(3))
LoadError: MethodError: `one` has no method matching one(::Type{Any})
while loading In[204], in expression starting on line 3

 in cg at /home/juser/.julia/v0.4/IterativeSolvers/src/cg.jl:3 (repeats 2 times)
```

**Comment by KristofferC** [comment]
I think you are better of creating a custom type that has the following interface (taken from the readme):

> A custom type for A may be specified. The following interface is expected to be defined on A:
>
>A*v is define and computes the matrix-vector product on a v::Vector.
>eltype(A) is defined and returns the element type implicit in the equivalent matrix representation of A.
>size(A, d) is defined and returns the nominal dimensions along the dth axis in the equivalent matrix representation of A.

**Comment by ajt60gaibb** [comment]
I tried that too and was running into problems.  I did not see #63, though. Thanks.
